### PR TITLE
Bigwigs ultrawide profile

### PR DESCRIPTION
**Pull request by RyadaProductions**
# Summary of Changes

1. Upon apply Bigwigs profile it sets the correct x coordinates for the bars/emphasizedbars and proximity

# Description

See summary of changes

# To test

- [ ] Check if profile applies correctly on 16:9
- [ ] Check if profile applies correctly on 21:9

### CODE REVIEW

**Comment by Toxicom** [comment]
Code looks logical. This opens up the question, probably a rhetorical one "should we do this for 1080p?" and the answer is most likely yes. Then I start thinking -- if we support 1080p, then why not 5xxx x something width? Basically, just wondering if we can calc this position and apply it on all resolutions

**Comment by RyadaProductions** [comment]
I was going to try and see if I can make a calculation to determine the logical positions of at least specifically these 3 parts, but I had to deal with rounding. I didn't know if I wanted to go for up or down rounding or if my calculation was bad, but that would be something I wanted to look for as an improvement after this PR. The bars I think should be doable, but the emphasized bars and the proximity are a bit more trial and error.

Forgot to add, in this case the vertical resolution is the same (so it still adheres to the designed for 1440p philosophy) while 1080p has a completely different vertical resolution so that would also need adjustment on the Y coordinate instead of just the X

**Comment by Toxicom** [comment]
> Forgot to add, in this case the vertical resolution is the same (so it still adheres to the designed for 1440p philosophy) while 1080p has a completely different vertical resolution so that would also need adjustment on the Y coordinate instead of just the X

We could have Y anchors move based on height, X anchors based on width?

**Comment by Toxicom** [comment]
Re-posting from discord here so it's documented:

I see two options moving forward:
**1) We think of a way to automatically generate X,Y positions for each resolution**
   - Pros: we cover every single possible resolution
   - Cons: like Lich mentioned, on some resolutions it doesn't make sense to have bars at the very edge of the screen

**2) We manually provide X,Y positions for each resolution**
   - Pros:
      - we have full control on where to position what
      - easier code-wise, meaning no surprises when generating a position
   - Cons: 
      - it's manual work
      - can't cover every single position
      - hard to test, users will have to provide positions and later test them

**Comment by RyadaProductions** [comment]
To be honest I do think the second option is the better long term solution as well
Purely based on the fact that we can say "this UI supports x resolution" and then it actually supports ultrawide, which generally ends up being forgotten about due to how much things go off to the side on some cases.
It's a more painful initial setup due to having to make some presets for each resolution breakpoint.

As for how I'm gonna go about it is I will rewrite the code that is in this PR to be more uniform and easily expandable instead of just a few values. After that I will create a list of all elements that need to be set to a specific position, and we can create a profile for 1440p (copy of the current profile) as well as one for UW (3440x1440) then we can ask some of our community members to pitch in for their own resolution so we can decide together where things should be placed on for example resolutions that have more than 5k pixels width.

**Pull request merged**
